language: python
python:
    - 2.7
    - 3.5
    - 3.6

os: linux

services: docker

install:
    - pip install -r requirements.txt

script:
    - python setup.py build
    - python setup.py install
    - python setup.py test
    - Corporate_WellDB_Log_Parser_Las lpl/tests/LAS30a.las
